# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env.local
    environment:
      POSTGRES_DB: pantry
      POSTGRES_USER: pantryuser
      POSTGRES_PASSWORD: ${DB_PASS:-YourPass}
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

  app:
    build:
      context: .
      target: production
    restart: on-failure
    env_file: .env.local
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

volumes:
  db-data:
