name: CI/CD to Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION:     ${{ secrets.GCP_REGION }}
  REPO:       ${{ secrets.GCP_AR_REPO }}
  SERVICE:    ${{ secrets.GCP_RUN_SERVICE }}
  IMAGE_TAG:  ${{ github.sha }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run build

  # 🔥 NEW: run migrations + seed against Cloud SQL
  db-seed:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v1

      - name: Download Cloud SQL Proxy
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.11.0/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy

      - name: Start proxy in background
        run: |
          INSTANCE="${{ env.PROJECT_ID }}:${{ env.REGION }}:pantrypal-db"
          ./cloud-sql-proxy --port=5432 $INSTANCE &
          echo "Proxy PID $!" > proxy.pid
          sleep 10

      - name: Install deps (needed for bcrypt)
        run: npm ci

      - name: Run migrate + seed
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          npx prisma migrate deploy --schema=prisma/schema.prisma
          node prisma/seed.js

      - name: Stop proxy
        if: always()
        run: kill $(cat proxy.pid)

  deploy:
    needs: [build-test, db-seed]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v1

      - name: Docker login
        run: |
          REGISTRY="${{ env.REGION }}-docker.pkg.dev"
          echo '${{ secrets.GCP_SA_KEY }}' | docker login -u _json_key --password-stdin "https://$REGISTRY"

      - name: Docker build & push
        run: |
          set -e
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE }}:${{ env.IMAGE_TAG }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image="$IMAGE" \
            --region="${{ env.REGION }}" \
            --platform=managed \
            --allow-unauthenticated \
            --add-cloudsql-instances="${{ env.PROJECT_ID }}:${{ env.REGION }}:pantrypal-db" \
            --set-env-vars=DATABASE_URL='${{ secrets.DATABASE_URL }}',JWT_SECRET='${{ secrets.JWT_SECRET }}',JWT_EXPIRES='${{ secrets.JWT_EXPIRES }}',REDIS_URL='${{ secrets.REDIS_URL }}',OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}' \
            --quiet
