name: CI/CD to Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION:     ${{ secrets.GCP_REGION }}
  REPO:       ${{ secrets.GCP_AR_REPO }}
  SERVICE:    ${{ secrets.GCP_RUN_SERVICE }}
  IMAGE_TAG:  ${{ github.sha }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
        name: Install deps
      - run: npm run lint
        name: Lint
      - run: npm run build
        name: Build

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      # 1️⃣ Authenticate to Google Cloud
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2️⃣ Install gcloud + Docker auth for Artifact Registry
      - uses: google-github-actions/setup-gcloud@v1
      - run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
        name: Configure Docker auth

      # 3️⃣ Build & push the image
      - run: |
          set -e
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE }}:${{ env.IMAGE_TAG }}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV   # share with next step
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
        name: Docker build & push

      # 4️⃣ Deploy to Cloud Run with the *exact* image we just pushed
      - run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image="$IMAGE" \
            --region="${{ env.REGION }}" \
            --platform=managed \
            --allow-unauthenticated \
            --quiet
        name: Deploy to Cloud Run
